### ISSUE TITLE
`eldev emacs` misbehaves if nested Emacs is started in terminal mode

### ISSUE THREAD

**Issue by lread** [doublep/eldev#89] opened 2023-07-04 19:28 UTC
## Thanks!
First, thanks for creating eldev, it seems like a really awesome idea and tool.

## Context
I am using eldev for the first time.
I am trying to replicate an issue I see with https://github.com/bbatsov/adoc-mode.
The adoc-mode project is setup for, and recommends eldev.

I am normally a doom emacs user and use evil key bindings.
I am not terribly familiar with emacs default key bindings and my confusion might be related to this.

## Versions
eldev 1.4.1
Emacs 28.2
Linux Pop!_OS 22.04

## What I've tried
I'm playing/learning in the adoc-mode project:
```Shell
git clone https://github.com/bbatsov/adoc-mode
cd adoc-mode
```

As a sanity test, I tried `eldev test`, it seems to work great.

But then, my idea is to run `eldev emacs` to interactively reproduce my issue with adoc-mode.

When I run `eldev emacs`, I see:

![image](https://github.com/doublep/eldev/assets/967328/1a35dc6e-d544-4da1-b57a-2a6d8abdd482)

The terminal seems a bit confused? If I type C-x C-f to open a file, I see ^X^F but no prompt for a file. The only command that seems to work for me it C-x C-c.

So I'm wondering:
1. Have I misunderstood `eldev emacs`?
2. Am I missing some config or terminal setting? I do see I have env var `TERM=xterm-256color`, are there other env vars I should be checking?

Any tips/help you might provide to this eldev noob are appreciated.

**Comment by doublep** [comment] 2023-07-04 19:41
Frankly, I never thought about running Emacs in a terminal mode. I can reproduce what you see if I execute `eldev emacs -nw`, but normally `eldev emacs` launches a fresh Emacs in a *window* (as in XWindows) mode for me. I have also tried that in `adoc-mode` now, worked like I would expect.

If you just type `emacs` in the command line, does it launch it in terminal mode? It looks like Eldev is kinda unprepared for that. I will look if I can do something about that, but that's not granted because of convoluted stdin/out/err handling in Elisp (Eldev is basically 99% Elisp).

**Comment by lread** [comment] 2023-07-04 21:07
Thanks so much for the speedy reply @doublep!

I used to run emacs in UI mode when I was on macOS.
I'll figure out how to build emacs with X support on Linux, retry and report back.

**Comment by lread** [comment] 2023-07-04 22:02
Ok, I reconfigured my emacs 28.2 build with:

```Shell
./configure --without-compress-install \
  --with-native-compilation \
  --with-json \
  --with-x \
  --with-xwidgets \
  --with-x-toolkit=gtk3 \
  --without-libgmp
```
The important bit is `--with-x` (and maybe `--with-x-toolkit` but the default might be gtk3 anyway).

And now `eldev emacs` seems to work!
![image](https://github.com/doublep/eldev/assets/967328/9910c94f-0e47-40fd-96fe-8b7ae84b233a)

Would you like me to PR a note in the eldev docs about `eldev emacs` requiring an emacs built with X support?

**Comment by lread** [comment] 2023-07-05 16:55
FWIW, I don't know how popular using emacs in terminal mode is.
Maybe I was an outlier. I've now switched to using emacs in UI mode.

**Comment by doublep** [comment] 2023-07-05 19:04
> Would you like me to PR a note in the eldev docs about eldev emacs requiring an emacs built with X support?

No, thank you, I'll just add this to documentation myself. Also, in future Eldev will warn about unsupported terminal mode or something, so please don't close the bug yet. (The problem is Eldev itself runs in batch-mode Emacs and it looks like it is impossible to start an "inner" Emacs in terminal mode from that. Or, rather, starting is not a problem, but making it work properly appears to be.)

> FWIW, I don't know how popular using emacs in terminal mode is. Maybe I was an outlier. I've now switched to using emacs in UI mode.

No idea, never used it myself other than maybe 3 times on some remote machines without X. No-one ever complained about this yet, but Eldev itself is not that popular, so lack of complaints here doesn't say much.

**Comment by doublep** [comment] 2023-07-20 17:28
Closing this as done. As of 1.5 Eldev will simply refuse to start terminal-mode Emacs and quit right away before breaking the terminal, with a hopefully somewhat useful diagnostic message. Would be nice to support that mode instead, of course, but I simply not see how that would be possible (currently).

**Closed by doublep** 2023-07-20 17:28 UTC
Labels: bug, apparently impossible in elisp

**Comment by lread** [comment] 2023-07-20 19:31
Thanks @doublep, I think that messaging will help confused newbies like me!
